TibzWeb/config/routes.rb
Insarce2::Application.routes.draw do

 get 'contact', :to => 'pages#contact', :as => "contact"

  get 'aide', :to => 'pages#aide', :as => "aide"
  
  get 'about', :to => 'pages#about', :as => "about"

  get 'rapport', :to => 'pages#rapport', :as => "rapport"

  devise_for :users

  get "home/index"

    resources :aperos 
    

    root :to => 'home#index'

end

TibzWeb/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  
 user ||= User.new # guest user (not logged in)

   
    if user.admin?
    can :manage, :all
    else
    can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

TibzWeb/app/models/apero.rb
class Apero < ActiveRecord::Base

  belongs_to :user
  belongs_to :category
  attr_accessible :category_id, :content, :date, :hour, :name, :user_id, :visibility
  validates :visibility, :presence => true
  validates :name, :presence => true
  validates :content, :presence => true
  validates :category_id, :numericality => { :less_than_or_equal_to => 3}
  validate :check_date
 

  def check_date
  	if date < Date.today
  		errors.add(:date, "can't be in the past")
  	end
  end
  
  def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end

  def self.visibility_types
     ['Amis', 'Public', 'Collegues']
  end

end

TibzWeb/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
end

TibzWeb/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  attr_accessible :id, :name

  def is_admin?
  	self.admin
  end
  
end

TibzWeb/app/controllers/aperos_controller.rb
class AperosController < ApplicationController
  # GET /aperos
  # GET /aperos.json

  helper_method :sort_column, :sort_direction
  before_filter :authenticate_user!, :except => [:index]
  load_and_authorize_resource

  def index
 
    @aperos = Apero.order(sort_column + " " + sort_direction)
    @aperos = Apero.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aperos }
    end
  end

  # GET /aperos/1
  # GET /aperos/1.json
  def show
    @apero = Apero.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @apero }
    end
  end

  # GET /aperos/new
  # GET /aperos/new.json
  def new
    @apero = Apero.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @apero }
    end
  end

  # GET /aperos/1/edit
  def edit
    @apero = Apero.find(params[:id])
  end

  # POST /aperos
  # POST /aperos.json
  def create
    @apero = Apero.new(params[:apero])
	@apero.user_id = current_user.id

    respond_to do |format|
      if @apero.save
        format.html { redirect_to @apero, notice: 'Apero was successfully created.' }
        format.json { render json: @apero, status: :created, location: @apero }
      else
        format.html { render action: "new" }
        format.json { render json: @apero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aperos/1
  # PUT /aperos/1.json
  def update
    @apero = Apero.find(params[:id])

    respond_to do |format|
      if @apero.update_attributes(params[:apero])
        format.html { redirect_to @apero, notice: 'Apero was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @apero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aperos/1
  # DELETE /aperos/1.json
  def destroy
    @apero = Apero.find(params[:id])
    @apero.destroy

    respond_to do |format|
      format.html { redirect_to aperos_url }
      format.json { head :no_content }
    end
  end

  private
  
  def sort_column
    Apero.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

TibzWeb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to root_url, :alert => exception.message

  	
  end
end

TibzWeb/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

TibzWeb/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def aide
  end

  def about
  end
end

TibzWeb/app/helpers/about_helper.rb
module AboutHelper
end

TibzWeb/app/helpers/aide_helper.rb
module AideHelper
end

TibzWeb/app/helpers/aperos_helper.rb
module AperosHelper
end

TibzWeb/app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
end

TibzWeb/app/helpers/contact_helper.rb
module ContactHelper
end

TibzWeb/app/helpers/home_helper.rb
module HomeHelper
end

TibzWeb/app/helpers/pages_helper.rb
module PagesHelper
end

TibzWeb/app/views/aperos/_form.html.erb
<%= form_for @apero, :html => { :class => 'form-horizontal' } do |f| %>

    <% if @apero.errors.any? %>
    <h2>Errors : </h2> 
    <ul>
    <% @apero.errors.full_messages.each do |message| %>
    <div class="alert alert-error">
    <li><%= message %></li>
    </div>
    <% end %>
    </ul>
    <% end %>

 
  <div class="control-group">
    <%= f.label :Nom, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :date, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Heure, :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :hour, :class => 'time_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Visibilité, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:visibility, Apero::visibility_types) %>
    </div>
  </div>
 
  <div class="control-group">
    <%= f.label :Categorie, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :category_id, Category.all.collect {|c| [c.name,c.id]}, {:include_blank => false}%>

    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                aperos_path, :class => 'btn' %>
  </div>
<% end %>

TibzWeb/app/views/aperos/edit.html.erb
<%- model_class = Apero -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Editer %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

TibzWeb/app/views/aperos/index.html.erb
<%- model_class = Apero -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= form_tag aperos_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Chercher", :name => nil %>
  </p>
<% end %>

<table class="table zebra-striped">
  <thead>
    <tr>
      <th><%= sortable "Nom" %></th>
      <th><%= sortable "Description" %></th>
      <th><%= sortable "Date" %></th>
      <th><%= sortable "Hour" %></th>
      <th><%= sortable "Visibilité" %></th>
      <th><%= sortable "ID_User" %></th>
      <th><%= sortable "Catégorie" %></th>
      <th><%= sortable "Créé à" %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @aperos.each do |apero| %>
      <tr>
      
        <td><%= apero.name %></td>
        <td><%= apero.content %></td>
        <td><%= apero.date %></td>
        <td><%= apero.hour %></td>
        <td><%= apero.visibility %></td>
        <td><%= User.find(apero.user_id).email %></td>
        <td><%= Category.find(apero.category_id).name %></td>
        <td><%=l apero.created_at %></td>
        <td>
          <% if user_signed_in? && current_user.is_admin? %>
            <%= link_to t('.Editer', :default => t("helpers.links.editer")),
                      edit_apero_path(apero), :class => 'btn btn-mini' %>
            <%= link_to t('.Supprimer', :default => t("helpers.links.destroy")),
                      apero_path(apero),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Etes vous sûr ?')) },
                      :class => 'btn btn-mini btn-danger' %>
                      <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")), new_apero_path,
            :class => 'btn btn-primary' %>

TibzWeb/app/views/aperos/new.html.erb
<%- model_class = Apero -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Nouveau %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

TibzWeb/app/views/aperos/show.html.erb
<%- model_class = Apero -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @apero.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @apero.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @apero.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hour) %>:</strong></dt>
  <dd><%= @apero.hour %></dd>
  <dt><strong><%= model_class.human_attribute_name(:visibility) %>:</strong></dt>
  <dd><%= @apero.visibility %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= User.find(@apero.user_id).email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @apero.category_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              aperos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_apero_path(@apero), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              apero_path(@apero),
              :method => 'Supprimer',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Etes vous sûr ?')) },
              :class => 'btn btn-danger' %>
</div>

TibzWeb/app/views/home/index.html.erb
<div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <P align="center">
          <img src="http://test.thecorpo.fr/site/files/6513/6117/8539/header_page_soiree.jpg" height="500" width="800" alt="">
          
          <div class="container">
            <div class="carousel-caption">
              <p class="lead">First</p>
            </div>
          </div>
        </div>
        <div class="item">
          <P align="center">
          <iframe width="640" height="360" src="https://www.youtube.com/embed/iNxvE-NvX-A?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>
          <div class="container">
            <div class="carousel-caption">
              <p class="lead">Second </p>
              
            </div>
          </div>
        </div>
        <div class="item">
          <P align="center">
          <img src="http://www.dtweb.fr/actu/wp-content/uploads/2013/04/google.jpg" height="500" width="800" alt="">
          <div class="container">
            <div class="carousel-caption">
              <p class="lead">Third</p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel -->
 <div class="span12">
<h1>Bienvenue sur INSAPERAVE </h1>
  <p>Organiser un apéro n'a jamais été aussi facile.

  Fini les chaînes d'emails interminables, les coups de fil intempestifs pour connaitre le lieu exact du rendez-vous ou le code d'en bas. Enfin tu sauras qui apportera le tire-bouchon et le vin rouge. 

  Organise tes apéros, tes dîners à la maison, tes picnics en trois étapes et invite tes amis simplement.</p>

  <p> Mais aussi s'authentifier si on veut <%= link_to "Apero index", aperos_path %> </p>

</div>

TibzWeb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aperoinsa</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="favicon.ico" rel="icon" type="image/x-icon" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
   <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="<%= root_url %>">AperoInsa</a>

          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a href="<%= aperos_path %>">Events</a></li>
              <li><a href="<%= new_apero_path %>">Créer un apéro</a></li>
              <% if !user_signed_in? %>
              <li><a href="<%= new_user_registration_path %>">Inscription</a></li>
              <%end%>

            </ul>
           <li class="nav pull-right">   
           <% if user_signed_in? %>
        <p class="navbar-text pull-right">
            Connecté en tant que <%= current_user.email %>. Ce n'est pas vous ?
            <%= link_to "Deconnexion", destroy_user_session_path %>
        </p>
            <% else %> 
            <%= form_for("user", :url => user_session_path, html: {class: 'navbar-form'}) do |f| %>
            <%= f.text_field :email, placeholder: 'Email', class: 'span2' %>
            <%= f.password_field :password, placeholder: 'Mot-de-passe', class: 'span2' %>
            <%= f.submit 'Connexion', class: 'btn' %>
            <% end %>

            
        <% end %>
        </li>
      </ul>


            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

  </div>
</div>
   <div class="container">
    <div class="row">
        <div class="span12"><%= yield %>
        </div>
    </div>
  </div>


 <div class="push"></div>
  </div>
  <div class="footer">
  <div class="container">
  <div class="page-header"> </div>
   <div> 
      <ul class="nav nav-pills">
        <li> <a href="<%= root_url %>">Home</a> </li>
        <li> <%= link_to "Aide-Apéro", aide_path %></li>
        <li> <%= link_to "Contact", contact_path %></li>
        <li > <%= link_to "A propos", about_path%> </a></li>
        <li > <%= link_to "Rapport", rapport_path%> </li>
              <div class='spread'>
 
    <form class ="nav-form pull-right">
      <div class='twshare left'>
        <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="funonrails">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
      </div>
      <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="" layout="button_count" show_faces="false" width="450" font=""></fb:like>
    </div>

      </ul>
   </div>
 </div>
</div>
</body >
</html>

TibzWeb/app/views/pages/about.html.erb
<div class ="container offset1">
<div class="span10" style="text-align:justify;">
<div class="page-header">
	<h1>Qui sommes nous ?</h1>
</div>

<p> <strong>AperoInsa</strong> est un service gratuit qui permet aux étudiants mais aussi aux professeurs de pouvoir organiser des soirées avec différents thèmes. Créer dans le cadre d'un projet d'étude par quatre étudiants de l'INSA Lyon, département Télécommunications, Services et Usages, AperoInsa n'a pas la prétention de concurrencer les sites qui proposent les mêmes prestations que nous.
</p>


<p> 
	Pour plus d'informations : <a <%= link_to "Contactez nous", contact_path %></a>

</p>

<p>
        © AperoInsa. Made with <a target="_blank" href="http://getbootstrap.com">Bootstrap.</a> </p>
</div>
</div>

TibzWeb/app/views/pages/aide.html.erb
<h1>Les 10 règles pour une home-party réussie</h1>


<div class="span12 pagination-centered">
	<IMG SRC="http://www.glamourparis.com/uploads/images/thumbs/201114/simon_winnall_getty_3646_north_584x0.jpg"
 class="img-circle" style="margin-bottom: 50px;">
</div>
<div class="span11" style="text-align:justify;">

<p align="justify">Organiser une petite sauterie à domicile, ça vous a toujours paru stressant et compliqué ? Hop, hop, hop, grâce à ce petit manuel en 10 étapes, vous n'aurez plus aucun raison de vous défiler.</p>

<p> <h3>1. On choisit THE date</h3>
C'est probablement l'un des éléments les plus importants d'une soirée réussie. Si peu de gens peuvent se libérer ce soir là, à priori, l'ambiance risque d'en prendre un coup. On la joue donc stratégique : bien sûr, on évite les jours de semaine, sous peine de voir ses invités qui travaillent le lendemain rentrer se coucher rapidement. Moins évident, on fait attention aux week-ends + jour férié, car même si l'on considère que les gens seront plus enclins à faire la fête en sachant qu'ils ont leur lundi de libre, quelques-uns en profiteront aussi pour se mettre au vert à ce moment-là. L'idéal est avant tout de prévenir suffisamment tôt pour que les copains réservent leur soirée, et de relancer tout le monde quelques jours avant, sans harcèlement. </p>      

<p align="justify"><h3><strong>2. On maîtrise la partie "invitation"</strong></h3>
Probablement l'étape la plus problématique. "Je mélange mes groupes d'amis ou pas ?", "J'ouvre la porte aux amis d'amis ?", "Je les préviens à quel moment ?", "Je crée une invitation sur Facebook ?", bref, un parquet de questions se posent. A moins d'avoir un groupe d'amis gigantesque, si l'on veut un peu de monde à notre petite sauterie, mieux vaut oser mélanger ses connaissances entre elles. De toute façon, la plupart du temps, nos invités sont aussi très contents de rencontrer de nouvelles têtes. Pour la question des "potes de potes", refuser à ses invités le droit de venir accompagnés risque un peu de les mettre mal à l'aise et de faire rabat-joie. Alors même si l'on a un petit appartement, on prend sur soi en disant que de toute façon, 45 personnes dans un 30 m2, ça rentre. Alors évidemment, être cool, c'est une chose, mais être "trop" cool, c'en est une autre. Pas question d'autoriser son ami Georges à ramener ses 13 potes alors qu'on n'en connait pas un seul, au risque de les voir vivre leur propre petite soirée dans leur coin.  
Créer un évènement annonçant sa fête sur Facebook, pourquoi pas, mais on ne compte pas uniquement dessus pour faire passer le message (déjà parce que tout le monde n'a pas Facebook, ensuite parce qu'on ne fait pas toujours très attention à cette fameuse page "Evènements"). Alors on fait passer le mot, on envoie des mails ou des petits textos, sans harcèlement (toujours). </p>

<p align="justify"><h3><strong>3. On évalue son budget</strong></h3>
L'idée, c'est bien sûr de limiter les dépenses en comptant sur les contributions alcoolisées de tout le monde. Sauf que dans les faits, ça ne se passe jamais comme on l'espère. On aura toujours forcément affaire aux 5 copines qui arrivent en même temps et qui pour seule denrée auront rapporté une bouteille de vinasse achetée 2,95 € chez l'épicier. En sachant que la plupart des invités ont cette fâcheuse tendance à apporter une bouteille de vin plutôt qu'une bouteille de vodka et que les bières viennent toujours à manquer à un moment dans le frigo, on n'hésite pas à préciser à chacun ce qu'il est préférable d'apporter, quitte à grouper les achats ("Ludo, Jérôme et Sophie, vous vous charger de prendre une bouteille de whisky ?", "Nico, tu ramènes un pack de bières ?", etc...). Du coup, on limite ses propres dépenses boissons et on s'assure de ne pas être à sec.
Point de vue buffet, mieux vaut être claire quant à la nature de la soirée : si on prévoit un vrai buffet bien garni, on prévient vraiment ses invités qu'il y aura à manger, histoire de ne pas se retrouver avec 23 kg de nourriture sur les bras. A l'inverse, on évite de vendre le côté "soirée-dîner" si l'on ne compte offrir que 3 chips et 5 cacahuètes. Les invités qui n'auraient pas assez mangé risqueraient d'ailleurs d'être ivres morts un peu trop vite.
</p>

<p align="justify"><h3><strong>4. On prépare le champ de bataille</strong></h3>
Une étape que l'on néglige souvent, à tord. Afin d'éviter les tâches de vin rouge sur le canapé, les  brûlures de cigarette sur le tapis ou la casse de son bibelot préféré, on protège ! Evidemment, pas question que son appart devienne une aire aseptisée où tout est recouvert de plastique, mais on n'hésite pas à déplacer les éléments fragiles dans une autre pièce (car même si "on a la flemme" sur le coup, on l'aura encore plus quand il sera question de réparer les dégâts). On recouvre donc le canapé, on roule les tapis, et on déplace tous les éléments fragiles. Si on veut éviter des drames, on évite aussi de mettre des bougies (surtout chauffe-plat, peu sécurisées) partout : dans l'euphorie, une bougie qui s'enflamme ne se remarque pas forcément tout de suite.
Le but, c'est aussi de faire de la place. Pour une soirée réussie, on DOIT prévoir un dance-floor pour bouger son corps.
</p>

<p align="justify"><h3><strong>5. On programme une chouette playlist (ou on désigne un DJ)</strong></h3>
Rien de pire que les soirées où tout le monde se bouscule devant les platines et s'acharne sur notre pauvre ordinateur portable. Au final, on se retrouve avec des morceaux coupés en plein milieu et une flopée de personnes qui n'en peut plus du monomaniaque du hip-hop qui a accaparé les commandes. Si on est motivée et sûre de nos choix (éclectiques, de préférence, on évite la playlist total disco ou années 80), on prépare donc une playlist qui pourra durer au moins deux heures. Si on n'a pas le courage, mieux vaut désigner un DJ qui pourra tout à fait tourner dans la soirée. Et pas d'inquiétude, les volontaires se trouvent beaucoup plus facilement qu'on ne le pense.</p>

<p align="justify"><h3><strong>6. On prévient les voisins</strong></h3>
Si cette petite précaution va de soi, on se doit tout de même de respecter quelques règles : un petit mot laissé dans l'ascenseur à 19h30 le jour J, ça ne sert pas à grand chose. Le mieux est de prévenir une bonne semaine avant, histoire de laisser le temps à ses voisins conciliants d'organiser leur soirée à l'extérieur. Si l'on sait par expérience que son voisinage n'est pas des plus tolérants, on peut aussi passer un coup de fil au commissariat le plus proche. Si la police est appelée pour nous faire une remontrance, elle se montrera plus compréhensive si elle a été prévenue...</p>

<p align="justify"><h3><strong>7. On se prépare sereinement</strong></h3>
Rien de pire que de devoir enfiler la première robe qu'on trouve et de finir de se maquiller alors que la sonnette retentit toutes les 5 minutes. Une bonne hôte se doit d'être prête dans les temps. On réfléchit donc à sa tenue à l'avance, et on prend bien le temps de se préparer pour ne pas stresser.  
</p>

<p align="justify"><h3><strong>8. On ne s'enferme pas dans le rôle de la "maîtresse de maison"</strong></h3>
A trop vouloir bien faire, on se retrouve souvent débordée. Servir des cocktails et apporter des vivres, ça va deux secondes. On tente donc de profiter de la soirée comme tout le monde, quitte à demander des coups de main à nos amis les plus proches. Le minimum syndical restant bien sûr de saluer tout le monde... Important, on évite aussi de s'imaginer toutes les heures à quoi ressemblera notre appart le lendemain matin. De toute façon, le mal est fait, Manu a déjà vomi derrière le fauteuil (et de tout façon, on a bien suivi à la lettre le précepte n°4, hein).</p>


<p align="justify"><h3><strong>9. On ne culpabilise pas</strong></h3>
Souvent, lorsque l'on rassemble des amis, on peut ressentir une certaine culpabilité à les avoir fait venir pour finalement ne leur parler que 10 minutes dans toute la soirée. Pas de panique. Les gens le savent. Quand on commence à se soucier du plaisir que les autres prennent (ou pas) à cette soirée, ça devient plus compliqué. A moins qu'il ne s'agisse de sa cousine venue exprès du Venezuela pour cette fête (motivée la cousine), on arrête de porter sur ses épaules la responsabilité de l'ennui de telle ou telle personne. Après tout, on a le droit de se marrer, et si pour eux ce n'est pas le cas, ça ne les tuera pas.</p>


<p><h3> <strong>10. Dernier point délicat </strong></h3> Virer en douceur les plus résistants (et les plus imbibés qui cuvent dans le canapé) quand on entend notre lit nous appeler. Généralement, quand on commence à esquisser quelques gestes de rangement (sans mettre une pression quelconque), ces derniers mettent leur manteau dans la minute. Et pour les plus soûls qui n'auront de toute façon pas la force de prendre un bus de nuit/taxi/vélo (et surtout pas un scooter ou une voiture), on prévoit un ou 2 duvets. Ils pourront toujours aider à passer la serpillère le lendemain...</p>
</div>

TibzWeb/app/views/pages/contact.html.erb
<h1>Nous contacter </h1>  

  			Guillaume DURY </br>
  			20 Avenue Albert Einstein  </br>
  			69100 VILLEURBANNE </br>
  			+33 6 71 46 74 68</br>
  			<p><a href="mailto:guillaume.dury@insa-lyon.fr">guillaume.dury@insa-lyon.fr</a></p> </br>

  			Thibault FORDEVEAUX</br>
  			20 Avenue Albert Einstein </br>
  			69100 VILLEURBANNE</br>
  			+33 6 67 25 39 43</br>
  			<p><a href="mailto:thibault.fordeveaux@insa-lyon.fr">thibault.fordeveaux@insa-lyon.fr </a></p> </br>

  			Pierre LITAUDON</br>
  			20 Avenue Albert Einstein </br>
  			69100 VILLEURBANNE</br>
  			+33 6 79 98 39 15</br>
  			<p><a href="mailto:pierre.litaudon@insa-lyon.fr">pierre.litaudon@insa-lyon.fr </a></p> </br>

  			Jean-Baptiste Lefeuvre</br>
  			13 rue Sala</br>
  			69100 </br>
  			+33 6 81 23 24 59 </br>
  			<p><a href="mailto:jean.baptiste@insa-lyon.fr">jean.baptiste@insa-lyon.fr</a></p> </br>