config/routes.rb
Blog::Application.routes.draw do
  get "pages/home"
  get "posts/index"
  match "home" => "pages#home", :as => "home"
  get "pages/more"

  get "pages/contact"

  devise_for :users
  
  resources :posts
  resources :components
  resources :pages
  resources :posts do
  collection { post :search, to: 'posts#index' }
  end
  resources :users
 
  root :to => "posts#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Guest User 
    unless user 
      can :read, :all
    else
      # All registered users
      can :create, Post
      can :create, Component
      can :manage, Post do |p|
      	p.try(:user) == user
    end
      
      can :read, :all
      # Admins 
      if user.is_admin?
        can :manage, :all
      end
    end  
end
end

app/models/component.rb
class Component < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :posts

  validates :name, :presence => true, :uniqueness => true
  UNRANSACKABLE_ATTRIBUTES = ["id", "created_at", "updated_at"]

   def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
 has_and_belongs_to_many :components
  attr_accessible :description, :difficulty, :name, :time, :component_ids, :id_user
  belongs_to :user

  validates :name, :presence => true, :uniqueness => true
  validates :difficulty,  :presence => true, :numericality => { :only_integer => true }
  validates :time, :presence => true, :numericality => { :only_integer => true }
  validates :description, :presence => true
  
  UNRANSACKABLE_ATTRIBUTES = ["id", "created_at", "updated_at", "description"]
   def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end			 
end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin, :post_ids
  has_many :posts
  RANSACKABLE_ATTRIBUTES = ["email"]
  def self.ransackable_attributes auth_object = nil
    RANSACKABLE_ATTRIBUTES + _ransackers.keys
  end			 
   def is_admin?
  	self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
  flash[:alert] = exception.message
  redirect_to root_url
  end
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  # GET /components
  # GET /components.json
  def index
    @components = Component.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @components }
    end
  end

  # GET /components/1
  # GET /components/1.json
  def show
    @component = Component.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @component }
    end
  end

  # GET /components/new
  # GET /components/new.json
  def new
    @component = Component.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @component }
    end
  end

  # GET /components/1/edit
  def edit
    @component = Component.find(params[:id])
  end

  # POST /components
  # POST /components.json
  def create
    @component = Component.new(params[:component])

    respond_to do |format|
      if @component.save
        format.html { redirect_to @component, notice: 'Component was successfully created.' }
        format.json { render json: @component, status: :created, location: @component }
      else
        format.html { render action: "new" }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /components/1
  # PUT /components/1.json
  def update
    @component = Component.find(params[:id])

    respond_to do |format|
      if @component.update_attributes(params[:component])
        format.html { redirect_to @component, notice: 'Component was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /components/1
  # DELETE /components/1.json
  def destroy
    @component = Component.find(params[:id])
    @component.destroy

    respond_to do |format|
      format.html { redirect_to components_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def more
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

# comments_controller.rb possibility

  # GET /posts
  # GET /posts.json
  def index
    @components = Component.includes(:post)
    @users = User.all
    @posts = Post.search(params[:search])
    @search = Post.search(params[:q])
    @posts = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end

     
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @components=Component.all 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @component = Component.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user = current_user

    respond_to do |format|
      if @post.save
        flash[:notice] = "Successfully created article."
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        flash[:notice] = "You don't have the rights to create a new Product"
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    params[:post][:component_ids] ||= []
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        flash[:notice] = "Successfully updated article"
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Successfully destroyed article"

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


def link_to_add_fields(name, f, type)
  new_object = f.object.send "build_#{type}"
  id = "new_#{type}"
  fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
    render(type.to_s + "_fields", f: builder)
  end
  link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
end


end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chemical Products</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body data-spy="scroll" data-target=".navbar">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">

        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
         <li class="brand"> <%= link_to "Chemistry", home_path %></li>
        <div class="nav-collapse">
          <ul class="nav">
           
            <li><%= link_to "Browse Products", posts_path %></li>

            <li><%= link_to "New Product", new_post_path %></li>
            
            <li><%= link_to "New Component", new_component_path %></li>

            <li><%= link_to "More" %></li>
          
          </ul>
            <p class="navbar-text pull-right">
            <% if user_signed_in? %>
            Signed in as <%= current_user.email %>. Not you?
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-danger btn-mini' %>
          <% else %>
            <%= link_to new_user_registration_path do %>
            <button class="btn-mini btn btn-info">Sign Up</button>
          <% end %>
            <%= link_to new_user_session_path do %>
            <button class="btn btn-info btn-mini">Sign In</button>
          <% end %>
          <% end %>
      </p>
        </div>
        
      </div>

    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
    </div>
  </div>
  <div class="push"></div>
                        </div>
                        <div class="footer">
                                <div class="container">


                                        <div class="page-header">
                                        </div>
                                        <div>
                                                <ul class="nav nav-pills">                                             
                                                    <li><%= link_to "About this website" %></li>
                                                    <li><%= link_to "Contact" %></li>
                                                </ul>
                                        </div>
                                </div>
                        </div>
</body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="hero-unit">
  <h1>Chemistry World</h1>
  <p>Wanna learn more about crazy experimentations ?
  <p>
    <div class="btn btn-primary btn-large">
      <%= link_to "It's Here", posts_path,{:style=>'color:#FFFFFF;', :class => "css_class"} %>
    </div>
  </p>
</div>

app/views/pages/more.html.erb
<h1>Pages#more</h1>
<p>Find me in app/views/pages/more.html.erb</p>

app/views/posts/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:components, :user]  %>
  <% end %>
  <%= f.predicate_select only: [:cont, :eq, :lt, :gt], compounds: false %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
<% if @post.errors.any? %>
  <ul>
      <% @post.errors.full_messages.each do |message| %>
      <div class="alert alert-error">
      <li><%= message %></li>
    </div>
      <% end %>
  </ul>
<% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :time, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :time, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :difficulty, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :difficulty, :class => 'number_field' %>
    </div>
  </div>

  <% for component in Component.find(:all) %>
  <div class="control-group">
    <%= check_box_tag "post[component_ids][]", component.id, @post.components.include?(component) %>
    <%= component.name %>
  </div>
  <% end %>
<!-- Components form -->
    


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">


  <h1><%=t '.title', :default => "Produits" %></h1>
</div> 
    <div>   
    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">
      Advanced Search 
    </button>
    </div>
  <div id="demo" class="collapse out">
    <%= search_form_for @search, url: search_posts_path, method: :post do |f| %>
      <%= f.condition_fields do |c| %>
        <%= render "condition_fields", f: c %>
      <% end %>
      <p><%= link_to_add_fields "Add Conditions", f, :condition %></p>
      <div class="field">
      Sort:
      <%= f.sort_fields do |s| %>
        <%= s.sort_select %>
      <% end %>
      </div>
      <div class="actions"><%= f.submit "Search" %></div>
    <% end %>
</div>

<table id="myTable" class="table table-striped tablesorter">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:time) %>(hours)</th>
      <th><%= model_class.human_attribute_name(:difficulty) %>(/10)</th>
      <th><%= model_class.human_attribute_name(:components) %></th>
      <th><%= model_class.human_attribute_name(:owner) %></th>
      <th><%= model_class.human_attribute_name(:creation_date) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.time %></td>
        <td><%= post.difficulty %></td>
        <td><%= post.components.map(&:name).join ', ' %>
        <td><%= post.user.try(:email) %></td>
        <td><%= post.created_at.day %>/<%= post.created_at.month %>/<%= post.created_at.year %>
        </td>
        <td> 
           <%= link_to t('.show', :default => t("helpers.links.show")),
                      post_path(post), :class => 'btn btn-mini' %>
      <% if can? :update, @post %>  
       <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-mini' %>
      <% end %>  
      <% if can? :destroy, @post %>  
       <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post,
                      method: :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
      <% end %>  
         
        </td>
      </tr>
    <% end %>
    <% if !user_signed_in? %>
      <div class="alert">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
        You must be logged in to edit posts!
      </div>
     <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.post', 'Nouveau Produit'], :model => model_class.model_name.human %></h1>
</div>

<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @post.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time) %>:</strong></dt>
  <dd><%= @post.time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @post.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:difficulty) %>:</strong></dt>
  <dd><%= @post.difficulty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:components) %>:</strong></dt>
  <dd><%= @post.components.map(&:name).join ', ' %></dd>
  <dt><strong><%= model_class.human_attribute_name(:owner) %>:</strong></dt>
  <dd><%= @post.user.try(:email) %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_post_path, :class => 'btn'  %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
  <% if user_signed_in? && current_user.is_admin? %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% end %>
</div>
<button class="btn btn-large btn-primary" type="button" href="http://www.oldspice.com/explosion" target="_blank">Test</button>